# Generated by Django 3.0.8 on 2020-10-19 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contripution', '0001_initial'),
        ('User', '0001_initial'),
        ('Team', '0001_initial'),
        ('Comment', '0001_initial'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(null=True)),
                ('detail', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('vedio', models.URLField()),
                ('category', models.ManyToManyField(to='Category.Categories')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comment.comments')),
                ('contributions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contripution.contribution')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Team.Team')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.Users')),
            ],
        ),
    ]
