# Generated by Django 3.0.8 on 2020-10-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contripution', '0001_initial'),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='comments',
        ),
        migrations.AlterField(
            model_name='projects',
            name='contributions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contripution.contribution'),
        ),
    ]
